id = "belyi_embedding"
title = "The absolute Galois group of the rationals embeds in the outer automorphism group of the free profinite group"
test = false
module = "LeanEval.NumberTheory.BelyiEmbedding"
holes = ["belyi_embedding"]
submitter = "Adam Topaz"
notes = "We call this the Belyi embedding because its existence is a consequence of Belyi's theorem."
